apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-blue
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
      version: blue
  template:
    metadata:
      labels:
        app: webapp
        version: blue
    spec:
      containers:
      - name: webapp
        image: gcr.io/causal-plating-357421/webapp:v1
        ports:
        - containerPort: 5000