apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-canary
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: gcr.io/causal-plating-357421/webapp:v3
        ports:
        - containerPort: 5000